[Mar 07 2022 11:14:18] - fish_dashboard_core - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\flask\app.py", line 1563, in try_trigger_before_first_request_functions
    self.ensure_sync(func)()
  File "C:\Users\tahjy\Documents\Starapple Projects\fish_dashboard\api\__init__.py", line 54, in populate_tables
    if len(s.query(Fish).all()) == 0:
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\session.py", line 2139, in query
    return self._query_cls(entities, self, **kwargs)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\query.py", line 180, in __init__
    self._set_entities(entities)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\query.py", line 187, in _set_entities
    self._raw_columns = [
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\query.py", line 188, in <listcomp>
    coercions.expect(
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 188, in expect
    resolved = impl._literal_coercion(
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 401, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 437, in _raise_for_expected
    return super(_SelectIsNotFrom, self)._raise_for_expected(
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 283, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Column expression or FROM clause expected, got <module 'api.models.Fish' from 'C:\\Users\\tahjy\\Documents\\Starapple Projects\\fish_dashboard\\api\\models\\Fish.py'>.
[Mar 07 2022 11:14:18] - fish_dashboard_core - ERROR - Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\flask\app.py", line 1563, in try_trigger_before_first_request_functions
    self.ensure_sync(func)()
  File "C:\Users\tahjy\Documents\Starapple Projects\fish_dashboard\api\__init__.py", line 54, in populate_tables
    if len(s.query(Fish).all()) == 0:
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\session.py", line 2139, in query
    return self._query_cls(entities, self, **kwargs)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\query.py", line 180, in __init__
    self._set_entities(entities)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\query.py", line 187, in _set_entities
    self._raw_columns = [
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\orm\query.py", line 188, in <listcomp>
    coercions.expect(
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 188, in expect
    resolved = impl._literal_coercion(
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 401, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 437, in _raise_for_expected
    return super(_SelectIsNotFrom, self)._raise_for_expected(
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\sql\coercions.py", line 283, in _raise_for_expected
    util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
  File "C:\Users\tahjy\.virtualenvs\fish_dashboard-CsoN7HN1\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: Column expression or FROM clause expected, got <module 'api.models.Fish' from 'C:\\Users\\tahjy\\Documents\\Starapple Projects\\fish_dashboard\\api\\models\\Fish.py'>.
